CREATE SCHEMA EC4_CC1M;
USE EC4_CC1M;

CREATE TABLE IF NOT EXISTS ALUNOS(
ALUNO_CPF VARCHAR(14),
ALUNO_MATRICULA INT,
PRIMARY KEY(CPF, MATRICULA),
ALUNO_NOME VARCHAR(40) NOT NULL,
ALUNO_DATA_NASC DATE NOT NULL,
ALUNO_CONTATO TEXT NOT NULL,
ALUNO_RUA VARCHAR(40) NOT NULL,
ALUNO_NUMRUA INT NOT NULL,
ALUNO_BAIRRO VARCHAR(40) NOT NULL,
ALUNO_CEP VARCHAR(9) NOT NULL,
ALUNO_CIDADE VARCHAR(40) NOT NULL,
ALUNO_ESTADO VARCHAR(40) NOT NULL,
ALUNO_PAIS VARCHAR(40) NOT NULL);


CREATE TABLE IF NOT EXISTS INSTRUTORES(
INST_REGISTRO INT PRIMARY KEY,
INST_NOME VARCHAR(40) NOT NULL,
INST_CPF INT UNIQUE NOT NULL,
INST_ESPECIALIDADE TEXT NOT NULL);


CREATE TABLE IF NOT EXISTS MODALIDADE(
MODAL_ID INT PRIMARY KEY,
MODAL_NOME VARCHAR(40),
MODAL_DESCRICAO TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS PLANO_DE_TREINAMENTO(
PLADT_ID INT PRIMARY KEY,
PLADT_DATAINICIO DATE NOT NULL,
PLADT_DATAFIM DATE NOT NULL,
PLADT_ALUNO INT NOT NULL,
PLADT_INSTRUTOR INT NOT NULL,
CONSTRAINT FK_ALUNO FOREIGN KEY(PLADT_ALUNO) REFERENCES ALUNOS(ALUNO_CPF),
CONSTRAINT FK_INSTRUTOR FOREIGN KEY(PLADT_INSTRUTOR) REFERENCES INSTRUTORES(INST_REGISTRO));


CREATE TABLE IF NOT EXISTS AULAS(
AULAS_ID INT PRIMARY KEY,
AULAS_HORARIO_INICIO TIME NOT NULL,
AULAS_HORARIO_FIM TIME NOT NULL,
AULAS_CAPAC_MAX INT NOT NULL,
AULAS_MODALIDADE INT NOT NULL,
AULAS_INSTRUTOR INT NOT NULL,
CONSTRAINT FK_MODALIDAE FOREIGN KEY(AULAS_MODALIDADE) REFERENCES MODALIDADE(MODAL_ID),
CONSTRAINT FK_INSTRUTOR FOREIGN KEY(AULAS_INSTRUTOR) REFERENCES INSTRUTORES(INST_REGISTRO));


CREATE TABLE IF NOT EXISTS PAGAMENTO(
PAG_ID INT PRIMARY KEY,
PAG_DATA DATE NOT NULL,
PAG_VALOR DECIMAL(10,3) NOT NULL,
PAG_STATUS ENUM('PAGO','PENDENTE'),
PAG_ALUNO INT NOT NULL,
CONSTRAINT FK_ALUNO FOREIGN KEY(PAG_ALUNO) REFERENCES ALUNOS(ALUNO_CPF));

CREATE TABLE IF NOT EXISTS ALUNOS_AULAS(
ALAU_AULAS INT,
ALAU_ALUNOS INT,
PRIMARY KEY(ALAU_AULAS, ALAU_ALUNOS),
ALAU_MATRI INT NOT NULL,
CONSTRAINT ALAU_FK_ALUNOS FOREIGN KEY(ALAU_ALUNOS) REFERENCES ALUNOS(ALUNO_CPF),
CONSTRAINT ALAU_FK_AULAS FOREIGN KEY(ALAU_AULAS) REFERENCES AULAS(AULA_ID));


CREATE TABLE IF NOT EXISTS INSTRUTORES_MODALIDADE(
INMD_INTRUTORES INT,
INMD_MODALDIADE INT,
PRIMARY KEY(INMD_INTRUTORES, INMD_MODALIDADE),
CONSTRAINT INMD_FK_INTRUTORES FOREIGN KEY(INMD_INSTRUTORES) REFERENCES INSTRUTORES(INST_REGISTRO),
CONSTRAINT INMD_FK_MODALIDADE FOREIGN KEY(INMD_MODALIDADE) REFERENCES MODALIDADE(MODAL_ID));

CREATE TABLE IF NOT EXISTS ALUNOS_MODALIDADE(
ALMD_ALUNOS INT,
ALMD_MODALIDADE INT,
PRIMARY KEY(ALMD_ALUNOS, ALMD_MODALIDADE),
ALMD_MATRICULA INT NOT NULL,
CONSTRAINT ALMD_FK_ALUNOS FOREIGN KEY(ALMD_ALUNOS) REFERENCES ALUNOS(ALUNO_CPF),
CONSTRAINT ALMD_FK_MODALIDADE FOREIGN KEY(ALMD_MODALIDADE) REFERENCES MODALIDADES(MODAL_ID));