CREATE SCHEMA EC4_CC1M;
USE EC4_CC1M;

CREATE TABLE IF NOT EXISTS ALUNOS(
ALUNO_CPF VARCHAR(14),
ALUNO_MATRICULA INT,
PRIMARY KEY(CPF, MATRICULA),
ALUNO_NOME VARCHAR(40) NOT NULL,
ALUNO_DATA_NASC DATE NOT NULL,
ALUNO_CONTATO TEXT NOT NULL,
ALUNO_RUA VARCHAR(40) NOT NULL,
ALUNO_NUMRUA INT NOT NULL,
ALUNO_BAIRRO VARCHAR(40) NOT NULL,
ALUNO_CEP VARCHAR(9) NOT NULL,
ALUNO_CIDADE VARCHAR(40) NOT NULL,
ALUNO_ESTADO VARCHAR(40) NOT NULL,
ALUNO_PAIS VARCHAR(40) NOT NULL);

ALTER TABLE EC4_CC1M.ALUNOS ADD COLUMN ALUNO_TESTE VARCHAR(50);
ALTER TABLE EC4_CC1M.ALUNOS MODIFY COLUMN ALUNO_TESTE INT;
ALTER TABLE EC4_CC1M.ALUNOS CHANGE COLUMN ALUNO_TESTE ALUNO_TESTE1 INT;
ALTER TABLE EC4_CC1M.ALUNOS DROP COLUMN ALUNO_TESTE1; 

CREATE TABLE IF NOT EXISTS INSTRUTORES(
INST_REGISTRO INT PRIMARY KEY,
INST_NOME VARCHAR(40) NOT NULL,
INST_CPF INT UNIQUE NOT NULL,
INST_ESPECIALIDADE TEXT NOT NULL);

ALTER TABLE EC4_CC1M.INSTRUTORES ADD COLUMN INST_TESTE VARCHAR(51);
ALTER TABLE EC4_CC1M.INSTRUTORES MODIFY COLUMN INST_TESTE INT;
ALTER TABLE EC4_CC1M.INSTRUTORES CHANGE COLUMN INST_TESTE INST_TESTE1 INT;
ALTER TABLE EC4_CC1M.INSTRUTORES DROP COLUMN INST_TESTE1; 


CREATE TABLE IF NOT EXISTS MODALIDADE(
MODAL_ID INT PRIMARY KEY,
MODAL_NOME VARCHAR(40),
MODAL_DESCRICAO TEXT NOT NULL);

ALTER TABLE EC4_CC1M.MODALIDADE ADD COLUMN MODAL_TESTE VARCHAR(52);
ALTER TABLE EC4_CC1M.MODALIDADE MODIFY COLUMN MODAL_TESTE INT;
ALTER TABLE EC4_CC1M.MODALIDADE CHANGE COLUMN MODAL_TESTE MODAL_TESTE1 INT;
ALTER TABLE EC4_CC1M.MODALIDADE DROP COLUMN MODAL_TESTE1; 

CREATE TABLE IF NOT EXISTS PLANO_DE_TREINAMENTO(
PLADT_ID INT PRIMARY KEY,
PLADT_DATAINICIO DATE NOT NULL,
PLADT_DATAFIM DATE NOT NULL,
PLADT_ALUNO INT NOT NULL,
PLADT_INSTRUTOR INT NOT NULL,
CONSTRAINT FK_ALUNO FOREIGN KEY(PLADT_ALUNO) REFERENCES ALUNOS(ALUNO_CPF),
CONSTRAINT FK_INSTRUTOR FOREIGN KEY(PLADT_INSTRUTOR) REFERENCES INSTRUTORES(INST_REGISTRO));

ALTER TABLE EC4_CC1M.PLANO_DE_TREINAMENTO ADD COLUMN PLADT_TESTE VARCHAR(53);
ALTER TABLE EC4_CC1M.PLANO_DE_TREINAMENTO MODIFY COLUMN PLADT_TESTE INT;
ALTER TABLE EC4_CC1M.PLANO_DE_TREINAMENTO CHANGE COLUMN PLADT_TESTE PLADT_TESTE1 INT;
ALTER TABLE EC4_CC1M.PLANO_DE_TREINAMENTO DROP COLUMN PLADT_TESTE1;


CREATE TABLE IF NOT EXISTS AULAS(
AULAS_ID INT PRIMARY KEY,
AULAS_HORARIO_INICIO TIME NOT NULL,
AULAS_HORARIO_FIM TIME NOT NULL,
AULAS_CAPAC_MAX INT NOT NULL,
AULAS_MODALIDADE INT NOT NULL,
AULAS_INSTRUTOR INT NOT NULL,
CONSTRAINT FK_MODALIDAE FOREIGN KEY(AULAS_MODALIDADE) REFERENCES MODALIDADE(MODAL_ID),
CONSTRAINT FK_INSTRUTOR FOREIGN KEY(AULAS_INSTRUTOR) REFERENCES INSTRUTORES(INST_REGISTRO));

ALTER TABLE EC4_CC1M.AULAS ADD COLUMN AULAS_TESTE VARCHAR(54);
ALTER TABLE EC4_CC1M.AULAS MODIFY COLUMN AULAS_TESTE INT;
ALTER TABLE EC4_CC1M.AULAS CHANGE COLUMN AULAS_TESTE AULAS_TESTE1 INT;
ALTER TABLE EC4_CC1M.AULAS DROP COLUMN AULAS_TESTE1;


CREATE TABLE IF NOT EXISTS PAGAMENTO(
PAG_ID INT PRIMARY KEY,
PAG_DATA DATE NOT NULL,
PAG_VALOR DECIMAL(10,3) NOT NULL,
PAG_STATUS ENUM('PAGO','PENDENTE'),
PAG_ALUNO INT NOT NULL,
CONSTRAINT FK_ALUNO FOREIGN KEY(PAG_ALUNO) REFERENCES ALUNOS(ALUNO_CPF));

ALTER TABLE EC4_CC1M.PAGAMENTO ADD COLUMN PAG_TESTE VARCHAR(55);
ALTER TABLE EC4_CC1M.PAGAMENTO MODIFY COLUMN PAG_TESTE INT;
ALTER TABLE EC4_CC1M.PAGAMENTO CHANGE COLUMN PAG_TESTE PAG_TESTE1 INT;
ALTER TABLE EC4_CC1M.PAGAMENTO DROP COLUMN PAG_TESTE1;

CREATE TABLE IF NOT EXISTS ALUNOS_AULAS(
ALAU_AULAS INT,
ALAU_ALUNOS INT,
PRIMARY KEY(ALAU_AULAS, ALAU_ALUNOS),
ALAU_MATRI INT NOT NULL,
CONSTRAINT ALAU_FK_ALUNOS FOREIGN KEY(ALAU_ALUNOS) REFERENCES ALUNOS(ALUNO_CPF),
CONSTRAINT ALAU_FK_AULAS FOREIGN KEY(ALAU_AULAS) REFERENCES AULAS(AULA_ID));

ALTER TABLE EC4_CC1M.ALUNOS_AULAS ADD COLUMN ALAU_TESTE VARCHAR(55);
ALTER TABLE EC4_CC1M.ALUNOS_AULAS MODIFY COLUMN ALAU_TESTE INT;
ALTER TABLE EC4_CC1M.ALUNOS_AULAS CHANGE COLUMN ALAU_TESTE ALAU_TESTE1 INT;
ALTER TABLE EC4_CC1M.ALUNOS_AULAS DROP COLUMN ALAU_TESTE1;


CREATE TABLE IF NOT EXISTS INSTRUTORES_MODALIDADE(
INMD_INTRUTORES INT,
INMD_MODALDIADE INT,
PRIMARY KEY(INMD_INTRUTORES, INMD_MODALIDADE),
CONSTRAINT INMD_FK_INTRUTORES FOREIGN KEY(INMD_INSTRUTORES) REFERENCES INSTRUTORES(INST_REGISTRO),
CONSTRAINT INMD_FK_MODALIDADE FOREIGN KEY(INMD_MODALIDADE) REFERENCES MODALIDADE(MODAL_ID));

ALTER TABLE EC4_CC1M.INSTRUTORES_MODALIDADE ADD COLUMN INMD_TESTE VARCHAR(56);
ALTER TABLE EC4_CC1M.INSTRUTORES_MODALIDADE MODIFY COLUMN INMD_TESTE INT;
ALTER TABLE EC4_CC1M.INSTRUTORES_MODALIDADE CHANGE COLUMN INMD_TESTE INMD_TESTE1 INT;
ALTER TABLE EC4_CC1M.INSTRUTORES_MODALIDADE DROP COLUMN INMD_TESTE1;


CREATE TABLE IF NOT EXISTS ALUNOS_MODALIDADE(
ALMD_ALUNOS INT,
ALMD_MODALIDADE INT,
PRIMARY KEY(ALMD_ALUNOS, ALMD_MODALIDADE),
ALMD_MATRICULA INT NOT NULL,
CONSTRAINT ALMD_FK_ALUNOS FOREIGN KEY(ALMD_ALUNOS) REFERENCES ALUNOS(ALUNO_CPF),
CONSTRAINT ALMD_FK_MODALIDADE FOREIGN KEY(ALMD_MODALIDADE) REFERENCES MODALIDADES(MODAL_ID));

ALTER TABLE EC4_CC1M.ALUNOS_MODALIDADE ADD COLUMN ALMD_TESTE VARCHAR(57);
ALTER TABLE EC4_CC1M.ALUNOS_MODALIDADE MODIFY COLUMN ALMD_TESTE INT;
ALTER TABLE EC4_CC1M.ALUNOS_MODALIDADE CHANGE COLUMN ALMD_TESTE ALMD_TESTE1 INT;
ALTER TABLE EC4_CC1M.ALUNOS_MODALIDADE DROP COLUMN ALMD_TESTE1;


CREATE TABLE IF NOT EXISTS TABELA_DROP4(
TESTE_DROP4 INT PRIMARY KEY,
TESTE_NOME4 VARCHAR(50) NOT NULL);


ALTER TABLE EC4_CC1M.TABELA_DROP4;