CREATE SCHEMA Fortes;
USE FORTE;



CREATE TABLE IF NOT EXISTS FUNCIONÁRIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_CPF INT NOT NULL,
FUNC_RUA VARCHAR(40) NOT NULL,
FUNC_NUMRUA INT NOT NULL,
FUNC_BAIRRO VARCHAR(40) NOT NULL,
FUNC_CEP VARCHAR(9) NOT NULL,
FUNC_CIDADE VARCHAR(40) NOT NULL,
FUNC_ESTADO VARCHAR(40) NOT NULL,
FUNC_PAIS VARCHAR(40) NOT NULL,
FUNC_CONTATO TEXT NOT NULL);



CREATE TABLE IF NOT EXISTS FORTES(
FORTES_CNPJ VARCHAR(14) PRIMARY KEY,
FORTES_RUA VARCHAR(40) NOT NULL,
FORTES_NUMRUA INT NOT NULL,
FORTES_BAIRRO VARCHAR(40) NOT NULL,
FORTES_CEP VARCHAR(9) NOT NULL,
FORTES_CIDADE VARCHAR(40) NOT NULL,
FORTES_ESTADO VARCHAR(40) NOT NULL,
FORTES_PAIS VARCHAR(40) NOT NULL);



CREATE TABLE IF NOT EXISTS DONATÁRIOS(
DONA_CNPJ VARCHAR(14) PRIMARY KEY,
DONA_PROJETOS TEXT NOT NULL,
DONA_RUA VARCHAR(40) NOT NULL,
DONA_NUMRUA INT NOT NULL,
DONA_CEP VARCHAR(9) NOT NULL,
DONA_BAIRRO VARCHAR(40) NOT NULL,
DONA_CIDADE VARCHAR(40) NOT NULL,
DONA_ESTADO VARCHAR(40) NOT NULL,
DONA_PAIS VARCHAR(40) NOT NULL);


CREATE TABLE IF NOT EXISTS PROJETOS_SOCIAIS(
PROJETOS_ID INT PRIMARY KEY,
PROJETOS_APROV ENUM('SIM', 'NAO') NOT NULL,
PROJETOS_DONA INT NOT NULL,
PROJETOS_FORTES INT NOT NULL,
CONSTRAINT FK_DONA FOREIGN KEY (PROJETOS_DONA) REFERENCES DONATÁRIOS(DONA_CNPJ),
CONSTRAINT FK_FORTES FOREIGN KEY (PROJETOS_FORTES) REFERENCES FORTES(FORTES_CNPJ));



CREATE TABLE IF NOT EXISTS EDITAIS(
EDITAL_ID INT PRIMARY KEY,
EDI_DATA_ABERT DATE NOT NULL,
EDI_DATA_FECHA DATE NOT NULL);


CREATE TABLE FUNCIONÁRIOS_PROJETOS (
FUNC_ID INT NOT NULL,
PROJETO_ID INT NOT NULL,
PRIMARY KEY (FUNC_ID, PROJETO_ID),
FOREIGN KEY (FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID),
FOREIGN KEY (PROJETO_ID) REFERENCES PROJETOS_SOCIAIS(PROJETO_ID));



CREATE TABLE DONATÁRIOS_EDITAIS (
DONA_CNPJ CHAR(14) NOT NULL,
EDITAL_ID INT NOT NULL,
PRIMARY KEY (DONA_CNPJ, EDITAL_ID),
FOREIGN KEY (DONA_CNPJ) REFERENCES DONATARIOS(DONA_CNPJ),
FOREIGN KEY (EDITAL_ID) REFERENCES EDITAIS(EDITAL_ID));