CREATE SCHEMA EC5_CC1M;
USE EC5_CC1M;

CREATE TABLE IF NOT EXISTS CLIENTE(
CLIE_CPF INT PRIMARY KEY,
CLIE_NOME VARCHAR(50) NOT NULL,
CLIE_DATA_NASC DATE NOT NULL,
CLIE_FIDELIDADE ENUM('ATIVO','INATIVO'),
CLIE_RUA VARCHAR(40) NOT NULL,
CLIE_NUMRUA INT NOT NULL,
CLIE_BAIRRO VARCHAR(40) NOT NULL,
CLIE_CEP VARCHAR(9),
CLIE_CIDADE VARCHAR(40) NOT NULL,
CLIE_ESTADO VARCHAR(40) NOT NULL,
CLIE_PAIS VARCHAR(20) NOT NULL);


CREATE TABLE IF NOT EXISTS FORNCEDOR(
FORNEC_ID INT PRIMARY KEY,
FORNEC_NOME VARCHAR(50) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL,
FORNEC_RUA VARCHAR(40) NOT NULL,
FORNEC_NUMRUA INT NOT NULL,
FORNEC_BAIRR VARCHAR(40) NOT NULL,
FORNEC_CEP VARCHAR(9) NOT NULL,
FORNEC_CIDADE VARCHAR(40) NOT NULL,
FORNEC_ESTADO VARCHAR(40) NOT NULL,
FORNEC_PAIS VARCHAR(20) NOT NULL);


CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_ID INT PRIMARY KEY,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_CATEGORIA TEXT NOT NULL,
PROD_PRECO DECIMAL(10,2) NOT NULL,
PROD_QUANT_ESTOQ INT NOT NULL,
PROD_FORNECEDOR INT NOT NULL,
CONSTRAINT FK_FORNECEDOR FOREIGN KEY(PROD_FORNECEDOR) REFERENCES FORNECEDOR(FORNEC_ID));


CREATE TABLE IF NOT EXISTS VENDAS(
VENDA_ID INT PRIMARY KEY,
VENDA_DATA DATE NOT NULL,
VENDA_FORMA_PAG VARCHAR(50) NOT NULL,
VENDA_VALOR_TOTAL DECIMAL(10,2) NOT NULL,
VENDA_CLIENTE INT NOT NULL,
CONSTRAINT FK_CLIENTE FOREIGN KEY(VENDA_CLIENTE) REFERENCES CLIENTE(CLIENTE_CPF));


CREATE TABLE IF NOT EXISTS PAGAMENTO(
PAG_ID INT PRIMARY KEY,
PAG_DATA DATE NOT NULL,
PAG_VALOR DECIMAL(10,2) NOT NULL,
PAG_STATUS ENUM('PENDENTE','PAGO'),
PAG_VENDA INT NOT NULL,
CONSTRAINT FK_VENDA FOREIGN KEY(PAG_VENDA) REFERENCES VENDAS(VENDA_ID));


CREATE TABLE IF NOT EXISTS VENDAS_PRODUTO(
VEPR_VENDAS INT NOT NULL,
VEPR_PRODUTO INT NOT NULL,
PRIMARY KEY(VEPR_VENDAS, VEPR_PRODUTO),
CONSTRAINT VEPR_FK_VENDAS FOREIGN KEY(VEPR_VENDAS) REFERENCES VENDAS(VENDA_ID),
CONSTRAINT VEPR_FK_PRODUTOS FOREIGN KEY(VEPR_PRODUTOS) REFERENCES PRODUTOS(PROD_ID));