CREATE SCHEMA EC3_CC1M;
USE EC3_CC1M;


CREATE TABLE IF NOT EXISTS CLIENTES(
CLIE_ID INT PRIMARY KEY,
CLIE_CNPJ INT NOT NULL,
CLIE_RAZAO_SOCIAL TEXT NOT NULL,
CLIE_RAMO_ATIVDADE TEXT NOT NULL,
CLIE_DATA_CADASTRO DATE NOT NULL);

ALTER TABLE EC3_CC1M.CLIENTES ADD COLUMN CLIE_TESTE VARCHAR(50);
ALTER TABLE EC3_CC1M.CLIENTES MODIFY COLUMN CLIE_TESTE INT;
ALTER TABLE EC3_CC1M.CLIENTES CHANGE COLUMN CLIE_TESTE CLIE_TESTE1 INT;
ALTER TABLE EC3_CC1M.CLIENTES DROP COLUMN CLIE_TESTE1;


CREATE TABLE IF NOT EXISTS EMPREGADOS(
EMPREG_ID INT PRIMARY KEY,
EMPREG_DATA_ADMISS DATE NOT NULL,
EMPREG_SALARIO INT NOT NULL,
EMPREG_QUALIFICAÇÃO TEXT NOT NULL);

ALTER TABLE EC3_CC1M.EMPREGADOS ADD COLUMN EMPREG_TESTE VARCHAR(51);
ALTER TABLE EC3_CC1M.EMPREGADOS MODIFY COLUMN EMPREG_TESTE INT;
ALTER TABLE EC3_CC1M.EMPREGADOS CHANGE COLUMN EMPREG_TESTE EMPREG_TESTE1 INT;
ALTER TABLE EC3_CC1M.EMPREGADOS DROP COLUMN EMPREG_TESTE1;


CREATE TABLE IF NOT EXISTS EMPRESAS(
EMPRE_CNPJ INT PRIMARY KEY,
EMPRE_RAZAO_SOCIAL TEXT NOT NULL);

ALTER TABLE EC3_CC1M.EMPRESAS ADD COLUMN EMPRE_TESTE VARCHAR(52);
ALTER TABLE EC3_CC1M.EMPRESAS MODIFY COLUMN EMPRE_TESTE INT;
ALTER TABLE EC3_CC1M.EMPRESAS CHANGE COLUMN EMPRE_TESTE EMPRE_TESTE1 INT;
ALTER TABLE EC3_CC1M.EMPRESAS DROP COLUMN EMPRE_TESTE1;


CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORNEC_CNPJ INT PRIMARY KEY,
FORNEC_RAZAO_SOCIAL TEXT NOT NULL);


ALTER TABLE EC3_CC1M.FORNECEDORES ADD COLUMN FORNEC_TESTE VARCHAR(54);
ALTER TABLE EC3_CC1M.FORNECEDORES MODIFY COLUMN FORNEC_TESTE INT;
ALTER TABLE EC3_CC1M.FORNECEDORES CHANGE COLUMN FORNEC_TESTE FORNEC_TESTE1 INT;
ALTER TABLE EC3_CC1M.FORNECEDORES DROP COLUMN FORNEC_TESTE1;


CREATE TABLE IF NOT EXISTS TELEFONES(
TELEF_ID INT NOT NULL,
TELEF_NUM INT NOT NULL,
TELEF_CLIENTE INT NOT NULL,
TELEF_FORNECEDOR INT NOT NULL,
TELEF_EMPRESA INT NOT NULL,
TELEF_EMPREGADO INT NOT NULL,
CONSTRAINT FK_CLIENTE FOREIGN KEY(TELEF_CLIENTE) REFERENCES CLIENTES(CLIE_ID),
CONSTRAINT FK_FORNECEDOR FOREIGN KEY(TELEF_FORNECEDOR) REFERENCES FORNECEDORES(FORNEC_CNPJ),
CONSTRAINT FK_EMPRESA FOREIGN KEY(TELEF_EMPRESA) REFERENCES EMPRESAS(EMPRE_CNPJ),
CONSTRAINT FK_EMPREGADO FOREIGN KEY(TELEF_EMPREGADO) REFERENCES EMPREGADOR(EMPREG_ID));


ALTER TABLE EC3_CC1M.TELEFONES ADD COLUMN TELEF_TESTE VARCHAR(55);
ALTER TABLE EC3_CC1M.TELEFONES MODIFY COLUMN TELEF_TESTE INT;
ALTER TABLE EC3_CC1M.TELEFONES CHANGE COLUMN TELEF_TESTE TELEF_TESTE1 INT;
ALTER TABLE EC3_CC1M.TELEFONES DROP COLUMN TELEF_TESTE1;


CREATE TABLE IF NOT EXISTS ENDEREÇO(
ENDEREC_RUA VARCHAR(40),
ENDEREC_NUMRUA INT NOT NULL,
ENDEREC_CEP VARCHAR(9) NOT NULL,
ENDEREC_BAIRRO VARCHAR(40),
ENDEREC_CIDADE VARCHAR(40),
ENDEREC_ESTADO VARCHAR(40),
ENDEREC_PAIS VARCHAR(40),
ENDEREC_CLIENTE INT NOT NULL,
ENDEREC_FORNECEDOR INT NOT NULL,
ENDEREC_EMPRESA INT NOT NULL,
ENDEREC_EMPREGADO INT NOT NULL,
CONSTRAINT FK_CLIENTE FOREIGN KEY(ENDEREC_CLIENTE) REFERENCES CLIENTES(CLIE_ID),
CONSTRAINT FK_FORNECEDOR FOREIGN KEY(ENDEREC_FORNECEDOR) REFERENCES FORNECEDORES(FORNEC_CNPJ),
CONSTRAINT FK_EMPRESA FOREIGN KEY(ENDEREC_EMPRESA) REFERENCES EMPRESAS(EMPRE_CNPJ),
CONSTRAINT FK_EMPREGADO FOREIGN KEY(ENDEREC_EMPREGADO) REFERENCES EMPREGADOS(EMPREG_ID));


ALTER TABLE EC3_CC1M.ENDEREÇO ADD COLUMN ENDEREC_TESTE VARCHAR(56);
ALTER TABLE EC3_CC1M.ENDEREÇO MODIFY COLUMN ENDEREC_TESTE INT;
ALTER TABLE EC3_CC1M.ENDEREÇO CHANGE COLUMN ENDEREC_TESTE ENDEREC_TESTE1 INT;
ALTER TABLE EC3_CC1M.ENDEREÇO DROP COLUMN ENDEREC_TESTE1;


CREATE TABLE IF NOT EXISTS PESSOA_DE_CONTATO(
PESSCT_ID INT NOT NULL,
PESSCT_CLIENTE INT NOT NULL,
PESSCT_FORNECEDOR INT NOT NULL,
PESSCT_EMPRESA INT NOT NULL,
CONSTRAINT  FK_CLIENTE FOREIGN KEY(PESSCT_CLIENTE) REFERENCES CLIENTES(CLIE_ID),
CONSTRAINT  FK_FORNECEDOR FOREIGN KEY(PESSCT_FORNECEDOR) REFERENCES FORNECEDORES(FORNEC_CNPJ),
CONSTRAINT  FK_EMPRESA FOREIGN KEY(PESSCT_EMPRESA) REFERENCES EMPRESA(EMPRE_CNPJ));


ALTER TABLE EC3_CC1M.PESSOA_DE_CONTATO ADD COLUMN PESSCT_TESTE VARCHAR(57);
ALTER TABLE EC3_CC1M.PESSOA_DE_CONTATO MODIFY COLUMN PESSCT_TESTE INT;
ALTER TABLE EC3_CC1M.PESSOA_DE_CONTATO CHANGE COLUMN PESSCT_TESTE PESSCT_TESTE1 INT;
ALTER TABLE EC3_CC1M.PESSOA_DE_CONTATO DROP COLUMN PESSCT_TESTE1;


CREATE TABLE IF NOT EXISTS TIPO_DE_ENDEREÇO(
TIPDENDEC_ID INT PRIMARY KEY,
TIPDENDEC_NOME VARCHAR(50) NOT NULL,
TIPDENDEC_CLIENTE INT NOT NULL,
TIPDENDEC_EMPREGADO INT NOT NULL,
TIPDENDEC_EMPRESA INT NOT NULL,
CONSTRAINT FK_CLIENTE FOREIGN KEY(TIPDENDEC_CLIENTE) REFERENCES CLIENTES(CLIE_ID),
CONSTRAINT FK_EMPREGADO FOREIGN KEY(TIPDENDEC_EMPREGADO) REFERENCES EMPREGADOS(EMPREG_ID),
CONSTRAINT FK_EMPRESA FOREIGN KEY(TIPDENDEC_EMPRESA) REFERENCES EMPRESAS(EMPRE_CNPJ));


ALTER TABLE EC3_CC1M.TIPO_DE_ENDEREÇO ADD COLUMN TIPDENDEC_TESTE VARCHAR(58);
ALTER TABLE EC3_CC1M.TIPO_DE_ENDEREÇO MODIFY COLUMN TIPDENDEC_TESTE INT;
ALTER TABLE EC3_CC1M.TIPO_DE_ENDEREÇO CHANGE COLUMN TIPDENDEC_TESTE TIPDENDEC_TESTE INT;
ALTER TABLE EC3_CC1M.TIPO_DE_ENDEREÇO DROP COLUMN TIPDENDEC_TESTE1;


CREATE TABLE IF NOT EXISTS ENCOMENDA(
ENCO_ID INT PRIMARY KEY,
ENCO_DATA_INCLUSAO DATE NOT NULL);


ALTER TABLE EC3_CC1M.ENCOMENDA ADD COLUMN ENCO_TESTE VARCHAR(59);
ALTER TABLE EC3_CC1M.ENCOMENDA MODIFY COLUMN ENCO_TESTE INT;
ALTER TABLE EC3_CC1M.ENCOMENDA CHANGE COLUMN ENCO_TESTE ENCO_TESTE INT;
ALTER TABLE EC3_CC1M.ENCOMENDA DROP COLUMN ENCO_TESTE1;


CREATE TABLE IF NOT EXISTS PAGAMENTOS(
PAG_ID INT PRIMARY KEY,
PAG_VALOR_LIQUIDO DECIMAL(10,2) NOT NULL,
PAG_VALOR_BRUTO DECIMAL(10,2) NOT NULL,
PAG_DESCONTOS DECIMAL(10,2) NOT NULL,
PAG_ENCOMENDA INT NOT NULL,
PAG_CLIENTE INT NOT NULL,
CONSTRAINT FK_CLIENTE FOREIGN KEY(PAG_CLIENTE) REFERENCES CLIENTE(CLIE_ID),
CONSTRAINT FK_ENCOMENDA FOREIGN KEY(PAG_ENCOMENDA) REFERENCES ENCOMENDA(ENCO_ID));


ALTER TABLE EC3_CC1M.PAGAMENTOS ADD COLUMN PAG_TESTE VARCHAR(60);
ALTER TABLE EC3_CC1M.PAGAMENTOS MODIFY COLUMN PAG_TESTE INT;
ALTER TABLE EC3_CC1M.PAGAMENTOS CHANGE COLUMN PAG_TESTE PAG_TESTE1 INT;
ALTER TABLE EC3_CC1M.PAGAMENTOS DROP COLUMN PAG_TESTE1;


CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_ID INT PRIMARY KEY,
PROD_PESO INT NOT NULL,
PROD_NOME VARCHAR(100) NOT NULL,
PROD_DIMENSAO TEXT NOT NULL,
PROD_COR VARCHAR(25) NOT NULL,
PROD_TEMP_FABRI DATETIME NOT NULL,
PROD_HO_MAO_D_OBRA TIME NOT NULL,
PROD_PRECO DECIMAL(10,2) NOT NULL,
PROD_DESEN_PROD TEXT NOT NULL);


ALTER TABLE EC3_CC1M.PRODUTOS ADD COLUMN PROD_TESTE VARCHAR(61);
ALTER TABLE EC3_CC1M.PRODUTOS MODIFY COLUMN PROD_TESTE INT;
ALTER TABLE EC3_CC1M.PRODUTOS CHANGE COLUMN PROD_TESTE PROD_TESTE1 INT;
ALTER TABLE EC3_CC1M.PRODUTOS DROP COLUMN PROD_TESTE1;


CREATE TABLE IF NOT EXISTS TIPO_D_COMPONENTE(
TIPODCOM_ID INT PRIMARY KEY,
TIPODCOM_NOME VARCHAR(100)NOT NULL);

ALTER TABLE EC3_CC1M.TIPO_D_COMPONENTE ADD COLUMN TIPODCOM_TESTE VARCHAR(62);
ALTER TABLE EC3_CC1M.TIPO_D_COMPONENTE MODIFY COLUMN TIPODCOM_TESTE INT;
ALTER TABLE EC3_CC1M.TIPO_D_COMPONENTE CHANGE COLUMN TIPODCOM_TESTE TIPODCOM_TESTE1 INT;
ALTER TABLE EC3_CC1M.TIPO_D_COMPONENTE DROP COLUMN TIPODCOM_TESTE1;


CREATE TABLE IF NOT EXISTS COMPONENTES(
COMPO_ID INT PRIMARY KEY,
COMPO_NOME VARCHAR(50) NOT NULL,
COMPO_UNIDADE INT NOT NULL,
COMPO_PREC_UNI INT NOT NULL,
COMPO_QUANT_ESTOQ TEXT NOT NULL);


ALTER TABLE EC3_CC1M.COMPONENTES ADD COLUMN COMPO_TESTE VARCHAR(63);
ALTER TABLE EC3_CC1M.COMPONENTES MODIFY COLUMN COMPO_TESTE INT;
ALTER TABLE EC3_CC1M.COMPONENTES CHANGE COLUMN COMPO_TESTE COMPO_TESTE1 INT;
ALTER TABLE EC3_CC1M.COMPONENTES DROP COLUMN COMPO_TESTE1;


CREATE TABLE IF NOT EXISTS MÁQUINAS(
MAQ_ID INT PRIMARY KEY,
MAQ_DATA_COMPRA DATE NOT NULL,
MAQ_FIM_GARANT DATE NOT NULL,
MAQ_TEMPO_VIDA DATETIME NOT NULL);


ALTER TABLE EC3_CC1M.MÁQUINAS ADD COLUMN MAQ_TESTE VARCHAR(63);
ALTER TABLE EC3_CC1M.MÁQUINAS MODIFY COLUMN MAQ_TESTE INT;
ALTER TABLE EC3_CC1M.MÁQUINAS CHANGE COLUMN MAQ_TESTE MAQ_TESTE1 INT;
ALTER TABLE EC3_CC1M.MÁQUINAS DROP COLUMN MAQ_TESTE1;


CREATE TABLE IF NOT EXISTS RECURSOS_ESPECIFICOS(
RE_QUANT_NECESS INT ,
RE_TEMPO_USO DATETIME NOT NULL,
RE_UNIDADE INT NOT NULL,
RE_HO_MAO_OBRA TIME NOT NULL,
RE_PRODUTOS INT NOT NULL,
CONSTRAINT FK_PRODUTOS FOREIGN KEY(RE_PRODUTOS) REFERENCES PRODUTOS(PROD_ID));


ALTER TABLE EC3_CC1M.RECURSOS_ESPECIFICOS ADD COLUMN RE_TESTE VARCHAR(63);
ALTER TABLE EC3_CC1M.RECURSOS_ESPECIFICOS MODIFY COLUMN RE_TESTE INT;
ALTER TABLE EC3_CC1M.RECURSOS_ESPECIFICOS CHANGE COLUMN RE_TESTE RE_TESTE1 INT;
ALTER TABLE EC3_CC1M.RECURSOS_ESPECIFICOS DROP COLUMN RE_TESTE1;


CREATE TABLE IF NOT EXISTS REGISTRO_DE_MANUTENÇÃO(
RM_DATA DATE NOT NULL,
RM_DESCRICAO TEXT NOT NULL,
RM_MAQUINA INT NOT NULL,
CONSTRAINT FK_MÁQUINAS FOREIGN KEY(RM_MAQUINA) REFERENCES MÁQUINAS(MAQ_ID));


CREATE TABLE IF NOT EXISTS REGISTRO_DE_SUPRIMENTOS(
RS_QUANT INT NOT NULL,
RS_DATA_NECESSI DATE NOT NULL,
RS_COMPONENTE INT NOT NULL,
CONSTRAINT FK_COMPONENTE FOREIGN KEY(RS_COMPONENTE) REFERENCES COMPONENTES(COMPO_ID));

#AGORA AS ENTIDADE ASSOCIATIVAS


CREATE TABLE IF NOT EXISTS COMPONENTES_TIPOdCOMPONENTE(
COTDC_COMPONENTES INT,
COTDC_TIPOD_COMPONENTE INT,
PRIMARY KEY (COTDC_COMPONENTES, COTDC_TIPOD_COMPONENTE),
CONSTRAINT COTDC_FK_COMPONENTES FOREIGN KEY(COTDC_COMPONENTES) REFERENCES COMPONENTES(COMPO_ID),
CONSTRAINT COTDC_FK_TIPOD_COMPONENTE FOREIGN KEY(COTDC_TIPOD_COMPONENTE) REFERENCES TIPO_D_COMPONENTE(TIPDENDEC_ID));


CREATE TABLE IF NOT EXISTS COMPONENTES_FORNECEDORES(
CPFR_COMPONENTES INT,
CPFR_FORNECEDOR INT,
PRIMARY KEY (CPFR_COMPONENTE, CPFR_FORNECEDOR),
CONSTRAINT CPFR_FK_COMPONENTES FOREIGN KEY(CPFR_COMPONENTES) REFERENCES COMPONENTES(COMPO_ID),
CONSTRAINT CPFR_FK_FORNECEDOR FOREIGN KEY(CPFR_FORNECEDOR) REFERENCES FORNECEDOR(FORNEC_CNPJ));


CREATE TABLE IF NOT EXISTS COMPONENTE_MÁQUINA(
CPMA_COMPONENTE INT,
CPMA_MAQUINA INT,
PRIMARY KEY (CPMA_COMPONENTE, CPMA_MAQUINA),
CONSTRAINT CPMA_FK_COMPONENTE FOREIGN KEY (CPMA_COMPONENTE) REFERENCES COMPONENTE(COMPO_ID),
CONSTRAINT CPMA_FK_MAQUINA FOREIGN KEY(CPMA_MAQUINA) REFERENCES MÁQUINAS(MAQ_ID));


CREATE TABLE IF NOT EXISTS MAQUINA_PRODUTO(
MQPR_MAQUINA INT,
MQPR_PRODUTO INT,
PRIMARY KEY(MQRE_MAQUINA, MQRE_PRODUTO),
CONSTRAINT MQRE_FK_MAQUINA FOREIGN KEY(MQRE_MAQUINA) REFERENCES MÁQUINAS(MAQ_ID),
CONSTRAINT MQRE_FK_PRODUTO FOREIGN KEY(MQRE_PRODUTO) REFERENCES PRODUTOS(PROD_ID));


CREATE TABLE IF NOT EXISTS PRODUTO_EMPREGADO(
PREM_PRODUTO INT,
PREM_EMPREGADO INT,
PRIMARY KEY(PREM_PRODUTO, PREM_EMPREGADO),
CONSTRAINT PREM_FK_PRODUTO FOREIGN KEY(PREM_PRODUTO) REFERENCES PRODUTOS(PROD_ID),
CONSTRAINT PREM_FK_EMPREGADO FOREIGN KEY(PREM_EMPREGADO) REFERENCES EMPREGADO(EMPREG_ID));


CREATE TABLE IF NOT EXISTS PRODUTO_ENCOMENDA(
PREC_PRODUTO INT,
PREC_ENCOMENDA INT,
PRIMARY KEY(PREC_PRODUTO, PREC_ENCOMENDA),
CONSTRAINT PREC_FK_PRODUTO FOREIGN KEY(PREC_PRODUTO) REFERENCES PRODUTOS(PROD_ID),
CONSTRAINT PREC_FK_ENCOMENDA FOREIGN KEY(PREC_ENCOMENDA) REFERENCES ENCOMENDA(ENCO_ID));